import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "src/styles/fonts";
import Header from "src/components/header";
import styles from "./page.module.css";
import { MdContactMail } from "react-icons/md";
import { FloatButton } from "src/components/float-button";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${styles.container}`}>
        <Header />

        <main>{children}</main>

        <FloatButton>
          <Link href='/contact'><MdContactMail className={styles.contact_icon} /></Link>
        </FloatButton>
      </body>
    </html>
  );
}
